version: '3'

services:

  client:
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    command: npm run dev
    volumes:
      - ./client/src:/app/src
    ports:
      - 3000:3000
    env_file: .env

  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    command: npm run dev
    volumes:
      - ./server/src:/app/src
    ports:
      - 5000:5000
    env_file: .env